#!/usr/bin/env bash

# tput setaf N
# 0 black
# 1 red
# 2 green
# 3 yellow
# 4 blue
# 5 magenta
# 6 cyan
# 7 white
# tput sgr0 (reset)

# Terminfo escape aliases
RESET="\[$(tput sgr0)\]"
# BLACK="\[$(tput setaf 0)\]"
RED="\[$(tput setaf 1)\]"
GREEN="\[$(tput setaf 2)\]"
YELLOW="\[$(tput setaf 3)\]"
# BLUE="\[$(tput setaf 4)\]"
# MAGENTA="\[$(tput setaf 5)\]"
CYAN="\[$(tput setaf 6)\]"
# WHITE="\[$(tput setaf 7)\]"

function exit_code_nonzero {
    echo -e "$CYAN\w $(ruby_version)$(git_branch_dirty)$RED\$ $RESET"
}

function exit_code_zero {
    echo -e "$CYAN\w $(ruby_version)$(git_branch_dirty)$GREEN\$ $RESET"
}

function gemscrub {
    gem pristine --all --env-shebang --no-extensions
}

function git_branch_dirty {
    # check in repo
    git rev-parse --is-inside-work-tree &>/dev/null || return

    # just branch name
    local branch
    # branch=$(git rev-parse --abbrev-ref HEAD)
    branch=$(git branch | sed -n '/\* /s///p')

    # dirty mark https://github.com/sindresorhus/pure
    local dirty
    dirty=$(test -n "$(command git status --porcelain --ignore-submodules --untracked-files=normal)" && echo "*")

    echo -e "$YELLOW$branch$dirty "
}

function display_notification {
    local text=$1
    local title=${2:-"Bash"}

    osascript -e 'on run argv' \
        -e 'display notification (item 1 of argv) with title (item 2 of argv)' \
        -e 'end run' \
        "$text" "$title"
}

function ruby_version {
    if [[ -n $RUBY_VERSION ]]; then
        echo -e "$RED$RUBY_VERSION "
    fi
}

function set_PS1 {
    if [[ $? == 0 ]]; then
        PS1=$(exit_code_zero)
    else
        PS1=$(exit_code_nonzero)
    fi
}

function vimplug {
    if [[ -n $1 ]]
    then
        case $1 in
            update | upgrade)
                vim +PlugUpdate +PlugClean! +PlugUpgrade +qall;;
            refresh)
                vim +PlugInstall +qall;;
            *)
                echo "Unknown command: $1"
        esac
    fi
}

stty -ixon
shopt -s histappend no_empty_cmd_completion

export CDPATH=".:~:~/code/fivegoodfriends:~/code/alexcruice"
export CLICOLOR="1"
export EDITOR="vim"
export HISTCONTROL="ignorespace:erasedups"
export HISTIGNORE="ls:bg:gf:history:exit"
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export LESS="--ignore-case --squeeze-blank-lines --LONG-PROMPT --RAW-CONTROL-CHARS"
export PAGER="less"
export PATH="$PATH:$HOME/bin"
GPG_TTY="$(tty)"
export GPG_TTY
export FZF_DEFAULT_COMMAND="ag --nocolor --files-with-matches"

source "/usr/local/etc/bash_completion"

source "/usr/local/opt/chruby/share/chruby/chruby.sh"
source "/usr/local/opt/chruby/share/chruby/auto.sh"

PROMPT_COMMAND="set_PS1;history -a;history -n"
eval "$(direnv hook bash)"
